services:
  neo4j:
    image: neo4j:latest
    deploy:
      resources:
        limits:
          memory: 4G
    volumes:
        - /$HOME/neo4j/logs:/logs
        - /$HOME/neo4j/config:/config
        - /$HOME/neo4j/data:/data
        - /$HOME/neo4j/plugins:/plugins
        - /$HOME/neo4j/import:/var/lib/neo4j/import
    environment:
        - NEO4J_AUTH=neo4j/your_password
        - NEO4J_PLUGINS=["apoc", "graph-data-science"]
        - NEO4J_server_memory_heap_initial__size=2G
        - NEO4J_server_memory_heap_max__size=2G
        - NEO4J_server_memory_pagecache_size=1G
        - NEO4J_apoc_import_file_enabled=true
        - NEO4J_dbms_security_procedures_unrestricted=gds.*,apoc.*
    ports:
      - "7474:7474"
      - "7687:7687"
    restart: always